const productsData = {
  cashews: { id: 'cashews', name: 'Premium Cashews', price: 349, rating: 5, reviews: 124, image: 'images/Cashews.png', desc: 'Whole premium W320 grade cashews directly from Konkan farms. Carefully roasted to preserve their natural creamy texture and rich flavor.', ingredients: '100% Cashew Nuts (W320 Grade)', origin: 'Sindhudurg, Maharashtra' },
  mango_pulp: { id: 'mango_pulp', name: 'Alphonso Mango Pulp', price: 229, rating: 4.5, reviews: 89, image: 'images/Mango Pulp.png', desc: '100% pure Alphonso mango pulp. Thick, natural, and sweetened just right without any artificial preservatives.', ingredients: 'Alphonso Mango (90%), Sugar (10%)', origin: 'Ratnagiri, Maharashtra' },
  kokum_syrup: { id: 'kokum_syrup', name: 'Kokum Sharbat', price: 199, rating: 5, reviews: 210, image: 'images/Kokum Syrup.png', desc: 'A cooling, refreshing traditional coastal drink concentrate made from sun-dried kokum and gently sweetened.', ingredients: 'Kokum Extract, Sugar, Water, Roasted Cumin', origin: 'Malvan, Maharashtra' },
  jackfruit_chips: { id: 'jackfruit_chips', name: 'Jackfruit Chips', price: 189, rating: 4, reviews: 64, image: 'images/JackfruitFries.png', desc: 'Crispy, thinly sliced golden jackfruit chips. Fried in fresh coconut oil with a pinch of salt.', ingredients: 'Raw Jackfruit, Coconut Oil, Salt', origin: 'Konkan Coast' },
  salted_cashews: { id: 'salted_cashews', name: 'Salted Cashews', price: 279, rating: 4.5, reviews: 142, image: 'images/Salted Cashews.png', desc: 'Lightly roasted and perfectly salted cashews for the ultimate crunch.', ingredients: 'Cashew Nuts, Pink Rock Salt', origin: 'Sindhudurg, Maharashtra' },
  choco_cashews: { id: 'choco_cashews', name: 'Choco Cashews', price: 299, rating: 5, reviews: 75, image: 'images/Choco Cashews.png', desc: 'Premium cashews coated in rich, dark chocolate for a sweet and nutty treat.', ingredients: 'Cashew Nuts, Dark Chocolate (Cocoa 55%)', origin: 'Konkan Coast' },
  kokum_butter: { id: 'kokum_butter', name: 'Kokum Butter', price: 399, rating: 5, reviews: 310, image: 'images/Kokum Butter.png', desc: 'Cold-pressed natural kokum butter. Highly moisturizing and pure, straight from the seed.', ingredients: '100% Pure Garcinia Indica Seed Butter', origin: 'Konkan Coast' },
  banana_chips: { id: 'banana_chips', name: 'Banana Chips', price: 120, rating: 4.5, reviews: 215, image: 'images/BananaChips.png', desc: 'Authentic Konkan style crispy banana chips seasoned perfectly and fried in pure coconut oil.', ingredients: 'Raw Banana, Coconut Oil, Salt, Turmeric', origin: 'Konkan Coast' }
};
